#pragma config(Sensor, dgtl1,  bottomLimitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  topLimitSwitch,  sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           craneMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// stop everything when button pressed
task bumpOff(){
	while(true){
		if(SensorValue(bumpSwitch) == 1){ //check if bumpswitch is pressed
			stopAllTasks();
		}
	}
}

// stop crane when arm hits the bottom or top limitSwitch limit switch
task armHitLimit(){
	while(true){
		if(SensorValue(bottomLimitSwitch) == 1 || SensorValue(topLimitSwitch) == 1){ // check if bottom limit switch is pressed
			stopMotor(craneMotor);
		}
	}
}

// using the potentiometer stop claw when it has completely opened and closed
task clawStop(){
  // TO-DO How to use potentiometer
}

// using the ultrasonic sensor stop robot when it gets close to a wall
task StopNearWall(){
  // TO-DO How to use ultrasonic
}

// DO THIS YOURSELF OR IN GROUPS AFTER WE HAVE COMPLETED STOPNEARWALL
// using the ultrasonic sensor turn robot when it gets close to a wall
task turnNearWall(){
  // TO-DO change the code from the stopNearWall task so that the robot turns instead of stops
}

// using Line Trackers (infrared sensors) have robot run until it hits dark floor
task findDarkFloor(){
  // TO-DO How to use Line Trackers
}

task main(){
  startTask(bumpOff);
  startTask(armHitLimit);
  motor[rightMotor] = 63;
  motor[rightMotor] = -63;
}
