#pragma config(Sensor, in8,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  bottomLimitSwitch, sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  topLimitSwitch, sensorTouch)
#pragma config(Sensor, dgtl4,  frontSonar,     sensorSONAR_inch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           craneMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int potVal = 0;
// stop everything when button pressed
task bumpOff(){
	while(true){
		if(SensorValue(bumpSwitch) == 1){ //check if bumpswitch is pressed
			stopAllTasks();
		}
	}
}

// stop crane when arm hits the bottom or top limitSwitch limit switch
task armHitLimit(){
	while(true){
		if(SensorValue(bottomLimitSwitch) == 1 || SensorValue(topLimitSwitch) == 1){ // check if bottom limit switch is pressed
			stopMotor(craneMotor);
		}
	}
}

// using the potentiometer stop claw when it has completely opened and closed
task clawStop(){
  while(true){
		potVal = SensorValue(clawPot);
		if(potVal >= 4095){
			motor[craneMotor] = 50;
			stopMotor(clawMotor);
			startMotor(clawMotor,30);
			wait10Msec(10);
			stopMotor(clawMotor);
		}
		if(potVal <= 0){
			motor[craneMotor] = -50;
			stopMotor(clawMotor);
			startMotor(clawMotor,-30);
			wait10Msec(10);
			stopMotor(clawMotor);
		}
	}
}
/*
// using the ultrasonic sensor stop robot when it gets close to a wall
task StopNearWall(){
  // TO-DO How to use ultrasonic
	while(true){
		int val = SensorValue(frontSonar); // get distance to wall from sonar
		if(val == 10){ // check if distance is less than 10 inches
			stopMotor(rightMotor); // stop movement when to close to wall
			stopMotor(leftMotor);
		}
	}
}

// DO THIS YOURSELF OR IN GROUPS AFTER WE HAVE COMPLETED STOPNEARWALL
// using the ultrasonic sensor turn robot when it gets close to a wall
task turnNearWall(){
  // TO-DO change the code from the stopNearWall task so that the robot turns instead of stops
}

// using Line Trackers (infrared sensors) have robot run until it hits dark floor
task findDarkFloor(){
  // TO-DO How to use Line Trackers
}
*/
task main(){
  startTask(bumpOff);
  startTask(armHitLimit);
  //startTask(clawStop);
  //startTask(StopNearWall);
  //motor[rightMotor] = 63;
  //motor[leftMotor] = 63;
  
  //startMotor(craneMotor,-50); //pos down neg up
  startMotor(clawMotor,50); // pos close neg opens
  wait10Msec(1000);
  
  //startMotor(clawMotor,50); // pos close neg opens
  //wait10Msec(1000);
}
